name: SLSA Provenance Test
on:
  push:
    branches: [main ]

permissions:
  contents: read
  actions: read
  id-token: write
  
jobs:
  generate-provenance:
    uses: slsa-framework/slsa-github-generator/ .github/workflows/generator_generic_slsa3.yml@v1.9.0
    with:
      artifact-path: build-output.txt
      private-repository: true
    secrets: inherit
