name: SLSA Provenance Test
on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write
  actions: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create a build artifact
        run: echo "This is my secure file" > build-output.txt

      - name: Calculate base64 SHA256 hash
        id: hash
        run: |
          HASH=$(sha256sum build-output.txt | cut -d ' ' -f1)
          HASH_ENCODED=$(echo -n "sha256:$HASH" | base64 -w0)
          echo "hashes=$HASH_ENCODED" >> $GITHUB_OUTPUT
        shell: bash

      - name: Debug print hash
        run: echo "Encoded hash is:${{ steps.hash.outputs.hashes }}"
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build-output.txt
          
  generate-provenance:
    needs: build
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
    with:
      base64-subjects: ${{ needs.build.outputs.hashes}}
      upload-assets: true
      private-repository: true
    permissions:
          contents: write
          id-token: write
          actions: read
