name: SLSA Provenance Test
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
  actions: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        
      - name: Create artifact
        run: echo "Secure artifact built at $(date)" > build-output.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build-output.txt
  generate-provenance:
    needs: build
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.10.0
    with:
      base64-subjects: false
      upload-assets: false
    permissions:
          id-token: write
          contents: write
          actions: read
