name: SLSA Provenance Test
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
  actions: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes}}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create a build artifact
        run: |
          echo "This is my secure file" > build-output.txt

      - name: Calculate base64-encoded SHA256 hash
        id: hash
        run: |
          DIGEST=$(sha256sum build-output.txt | cut -d ' ' -f1)
          echo "hashes=$(echo -n 'sha256:$DIGEST' | base64 -w0)" >> $GITHUB_OUTPUT
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build-output.txt
  generate-provenance:
    needs: build
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
    with:
      base64-subjects: ${{ needs.build.outputs.hashes}}
      upload-assets: false
      private-repository: true
    permissions:
          id-token: write
          contents: write
          actions: read
