name: SLSA Provenance Test
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        
      - name: Create artifact
        run: |
          echo "Secure artifact built at $(date)" > build-output.text
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build-output.text
          
      - name: Generate provenance
        uses: slsa-framework/slsa-github-generator/.github/workflows/slsa3-provenance-generic.yaml@v1.7.0
        with: 
           artifact_path: build-output.txt
           base64-subjects: false
           upload-assets: false
