name: SBOM Generator

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Recreate build artifact
        run: echo "This is a secure build artifact" > build-output.txt

      - name: Install Syft
        run:
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM (SPDX JSON)
        run: syft file:./build-output.txt -o spdx-json > sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
